from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    CourseViewSet,
    LogViewSet,
    SessionViewSet,
    auth_logout,
    auth_status,
    combined_day_preview,
    combined_day_publish,
    get_import_batch,
    google_auth_callback,
    google_auth_start,
    import_file_preview,
    import_google_sheet_commit,
    import_google_sheet_preview,
    list_import_batches,
    promote_import_batch,
)
from .admin_views import (
    # Groups
    list_groups,
    sync_groups,
    add_member_to_group,
    remove_member_from_group,
    list_group_members,
    # Classroom admin
    list_classroom_courses,
    list_classroom_course_roster,
    add_student_to_course,
    add_teacher_to_course,
    # Bundles
    list_bundles,
    create_bundle,
    update_bundle,
    delete_bundle,
    # Commands
    commands_preview,
    commands_run,
    list_jobs,
    get_job,
    list_command_logs,
    retry_job,
    # CSV Import
    csv_import_preview,
    csv_import_run,
    # Phase 2B — Classroom lifecycle + removal
    classroom_preflight,
    create_course_view,
    archive_course_view,
    delete_course_view,
    remove_student_view,
    remove_teacher_view,
)
from .directory_views import (
    approve_directory_issue,
    approve_directory_approval_request,
    bulk_approve_directory_issues,
    cancel_directory_approval_request,
    directory_stats,
    directory_sync,
    get_directory_sync_job,
    list_directory_sync_jobs,
    directory_approval_request_detail,
    directory_approval_requests,
    directory_user_detail,
    email_template_rule_detail,
    email_template_rules,
    execute_directory_change_job,
    get_directory_audit_log,
    get_directory_change_job,
    get_directory_issue,
    get_provisioning_record,
    list_directory_audit_logs,
    list_directory_change_jobs,
    list_directory_issues,
    list_directory_users,
    list_provisioning_records,
    mark_exception_directory_issue,
    org_unit_template_detail,
    org_unit_templates,
    preview_directory_change_job,
    provisioning_bulk_create,
    provisioning_bulk_preview,
    provisioning_create,
    provisioning_preview,
    reject_directory_issue,
    reject_directory_approval_request,
    scan_directory_issues,
    verify_upload_directory,
    list_directory_verify_jobs,
    get_directory_verify_job,
    list_directory_verify_rows,
    export_directory_verify_job,
)

router = DefaultRouter()
router.register("classrooms", CourseViewSet, basename="classrooms")
router.register("sessions", SessionViewSet, basename="sessions")
router.register("logs", LogViewSet, basename="logs")

urlpatterns = [
    path("auth/google/start", google_auth_start),
    path("auth/google/callback", google_auth_callback),
    path("auth/status", auth_status),
    path("auth/logout", auth_logout),
    # Import endpoints
    path("imports/google-sheet/preview", import_google_sheet_preview),
    path("imports/file/preview", import_file_preview),
    path("imports/google-sheet/commit", import_google_sheet_commit),
    path("imports/", list_import_batches),
    path("imports/<int:batch_id>/", get_import_batch),
    path("imports/<int:batch_id>/promote/", promote_import_batch),
    # Publish — combined-day message
    path("publish/combined-day-preview", combined_day_preview),
    path("publish/combined-day-post", combined_day_publish),
    # Phase 2 — Groups
    path("groups", list_groups),
    path("groups/sync", sync_groups),
    path("groups/add-member", add_member_to_group),
    path("groups/remove-member", remove_member_from_group),
    path("groups/<str:group_email>/members", list_group_members),
    # Phase 2 — Classroom Admin
    path("classroom/courses", list_classroom_courses),
    path("classroom/courses/<str:course_id>/roster", list_classroom_course_roster),
    path("classroom/add-student", add_student_to_course),
    path("classroom/add-teacher", add_teacher_to_course),
    # Phase 2 — Bundles
    path("bundles", list_bundles),
    path("bundles/create", create_bundle),
    path("bundles/<int:bundle_id>", update_bundle),
    path("bundles/<int:bundle_id>/delete", delete_bundle),
    # Phase 2 — Commands
    path("commands/preview", commands_preview),
    path("commands/run", commands_run),
    path("commands/jobs", list_jobs),
    path("commands/jobs/<int:job_id>", get_job),
    path("commands/logs", list_command_logs),
    path("commands/retry", retry_job),
    # Phase 2 — CSV Import
    path("commands/import/csv/preview", csv_import_preview),
    path("commands/import/csv/run", csv_import_run),
    # Phase 2B — Classroom lifecycle + direct removal
    path("classroom/preflight", classroom_preflight),
    path("classroom/courses/create", create_course_view),
    path("classroom/courses/<str:course_id>/archive", archive_course_view),
    path("classroom/courses/<str:course_id>", delete_course_view),
    path("classroom/remove-student", remove_student_view),
    path("classroom/remove-teacher", remove_teacher_view),
    # Module B — Directory Operations
    path("directory/users", list_directory_users),
    path("directory/users/<int:user_id>", directory_user_detail),
    path("directory/sync", directory_sync),
    path("directory/sync-jobs", list_directory_sync_jobs),
    path("directory/sync-jobs/<int:job_id>", get_directory_sync_job),
    path("directory/stats", directory_stats),
    path("directory/issues", list_directory_issues),
    path("directory/issues/scan", scan_directory_issues),
    path("directory/issues/bulk-approve", bulk_approve_directory_issues),
    path("directory/issues/<int:issue_id>", get_directory_issue),
    path("directory/issues/<int:issue_id>/approve", approve_directory_issue),
    path("directory/issues/<int:issue_id>/reject", reject_directory_issue),
    path("directory/issues/<int:issue_id>/mark-exception", mark_exception_directory_issue),
    path("org-units/templates", org_unit_templates),
    path("org-units/templates/<int:template_id>", org_unit_template_detail),
    path("email-templates", email_template_rules),
    path("email-templates/<int:rule_id>", email_template_rule_detail),
    path("directory/change-jobs/preview", preview_directory_change_job),
    path("directory/change-jobs/execute", execute_directory_change_job),
    path("directory/change-jobs", list_directory_change_jobs),
    path("directory/change-jobs/<int:job_id>", get_directory_change_job),
    path("directory/approvals", directory_approval_requests),
    path("directory/approvals/<int:approval_request_id>", directory_approval_request_detail),
    path("directory/approvals/<int:approval_request_id>/approve", approve_directory_approval_request),
    path("directory/approvals/<int:approval_request_id>/reject", reject_directory_approval_request),
    path("directory/approvals/<int:approval_request_id>/cancel", cancel_directory_approval_request),
    path("provisioning/preview", provisioning_preview),
    path("provisioning/create", provisioning_create),
    path("provisioning/bulk-preview", provisioning_bulk_preview),
    path("provisioning/bulk-create", provisioning_bulk_create),
    path("provisioning/records", list_provisioning_records),
    path("provisioning/records/<int:record_id>", get_provisioning_record),
    path("directory/audit-logs", list_directory_audit_logs),
    path("directory/audit-logs/<int:log_id>", get_directory_audit_log),
    path("directory/verify-upload", verify_upload_directory),
    path("directory/verify-jobs", list_directory_verify_jobs),
    path("directory/verify-jobs/<int:job_id>", get_directory_verify_job),
    path("directory/verify-jobs/<int:job_id>/rows", list_directory_verify_rows),
    path("directory/verify-jobs/<int:job_id>/export", export_directory_verify_job),
    path("", include(router.urls)),
]
