# Generated by Django 4.2.29 on 2026-03-14 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_directorychangejob_directoryuser_emailtemplaterule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryauditlog',
            name='linked_change_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.directorychangejob'),
        ),
        migrations.AddField(
            model_name='directoryauditlog',
            name='linked_provisioning_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.provisioningrecord'),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bulk_change_job_execute', 'Bulk Change Job Execute'), ('bulk_provisioning_create', 'Bulk Provisioning Create'), ('high_risk_mutation', 'High Risk Mutation')], max_length=100)),
                ('target_type', models.CharField(choices=[('change_job', 'Change Job'), ('provisioning_batch', 'Provisioning Batch'), ('mutation_scope', 'Mutation Scope')], max_length=50)),
                ('target_reference', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('executed', 'Executed'), ('execution_failed', 'Execution Failed')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('execution_status', models.CharField(choices=[('not_started', 'Not Started'), ('ready_to_execute', 'Ready To Execute'), ('executed', 'Executed'), ('execution_failed', 'Execution Failed')], default='not_started', max_length=30)),
                ('execution_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_change_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='core.directorychangejob')),
                ('linked_provisioning_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='core.provisioningrecord')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='directoryauditlog',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.approvalrequest'),
        ),
    ]
