# Generated by Django 5.1.6 on 2026-03-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_directoryauditlog_linked_change_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryuser",
            name="aliases_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="normalized_email",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="normalized_full_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="normalized_phone",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="directoryuser",
            name="phones_json",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="DirectorySyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="queued", max_length=20)),
                ("query", models.CharField(blank=True, max_length=255)),
                ("max_results", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("pages_fetched", models.IntegerField(default=0)),
                ("users_fetched_total", models.IntegerField(default=0)),
                ("users_upserted_total", models.IntegerField(default=0)),
                ("users_created_total", models.IntegerField(default=0)),
                ("users_updated_total", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("result_summary_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="directory_sync_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryVerifyJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_filename", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=20)),
                ("status", models.CharField(choices=[("uploaded", "Uploaded"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="uploaded", max_length=20)),
                ("row_count", models.IntegerField(default=0)),
                ("summary_json", models.JSONField(default=dict)),
                ("column_mapping_json", models.JSONField(default=dict)),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="directory_verify_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryVerifyRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_no", models.IntegerField()),
                ("input_json", models.JSONField(default=dict)),
                ("matched_email", models.CharField(blank=True, max_length=255)),
                ("matched_name", models.CharField(blank=True, max_length=255)),
                ("match_basis", models.CharField(blank=True, max_length=50)),
                ("verdict", models.CharField(choices=[("exists", "Exists"), ("does_not_exist", "Does Not Exist"), ("ambiguous", "Ambiguous"), ("invalid_input", "Invalid Input")], max_length=30)),
                ("confidence_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="core.directoryverifyjob")),
                ("matched_directory_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verify_rows", to="core.directoryuser")),
            ],
            options={
                "ordering": ["row_no", "id"],
            },
        ),
    ]
